# Intro to Numpy

Try attempting the exercises below to help you build your confidence when working with Numpy Arrays.

We may not have covered everything below, so you will have to use your preferred search engine to find the solution(s)!

Here's a list of references that might help you with the exercises below:

* [Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)
* [Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)
* [Google Search](https://www.google.com/search?q=how+to+use+numpy)

#### First things first... Import Numpy. Given it the alias `np`.

In [ ]:
# your code here

#### Print your NumPy version.

*Hint:* Google is your friend. [Isn't it?](https://www.google.com/search?q=print+numpy+version&oq=print+numpy+version)

In [ ]:
# your code here

#### Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *`a`*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [ ]:
# your code here

#### Print `a`.

In [ ]:
# your code here

#### Create a 5x2x3 3-dimensional array of 1s (i.e., all elements are 1). Assign the array to variable *`b`*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [ ]:
# your code here

#### Print `b`.

In [ ]:
# your code here

#### Do *`a`* and *`b`* have the same size? How do you prove that in Python code?

In [ ]:
# your answer and code here

#### Are you able to add *a* and *b*? Why or why not?

In [ ]:
# your answer here

No - they are not the same shape.... See https://www.educative.io/answers/how-to-add-one-array-to-another-array-in-python

#### Transpose *`b`* so that it has the same structure of *`a`* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

*Hint*: search for `np.transpose`

In [ ]:
# your code here

#### Try to add *`a`* and *`c`*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your answer and code here

#### Print *`a`* and *`d`*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code here

#### Multiply *`a`* and *`c`*. Assign the result to *`e`*.

In [ ]:
# your code here

#### Does *`e`* equal to *`a` *? Why or why not?

In [ ]:
# your code answer here

#### Identify the max, min, and mean values in *d`*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### Now we want to label the values in *d*. 
*First create an empty array `f`* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.



In [ ]:
# your code here

Next, for each value in *`d`*, if it's larger than *`d_min`* but smaller than *`d_mean`*, assign 25 to the corresponding value in *`f`*. If a value in *`d`* is larger than *`d_mean`* but smaller than *`d_max`*, assign 75 to the corresponding value in *`f`*. If a value equals to *`d_mean`*, assign 50 to the corresponding value in *`f`*. Assign 0 to the corresponding value(s) in *`f`* for *`d_min`* in *`d`*. Assign 100 to the corresponding value(s) in *`f`* for *`d_max`* in *`d`*. In the end, `f` should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

The end.